version: '3.7'

services:
  salt-master:
    build: .
    container_name: salt-master
    hostname: salt
    ports:
      - 4505:4505
      - 4506:4506
    volumes:
      - ./master/master.d:/etc/salt/master.d
      - ./master/salt:/srv/salt
      - ./master/pillar:/srv/pillar
      - keys:/etc/salt/pki/master
    environment:
      - SALT_LOG_LEVEL=debug

volumes:
  keys:
